
name: Integration Tests

on:
  pull_request:
    branches: [ "master" ]

jobs:
  integration-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm install
    - run: npm run integration
      env:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        FUNCTION_UUID: ${{ secrets.FUNCTION_UUID }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        OAUTH_API_KEY: ${{ secrets.OAUTH_API_KEY }}
        OAUTH_API_SECRET: ${{ secrets.OAUTH_API_SECRET }}
        OAUTH_TOKEN_KEY: ${{ secrets.OAUTH_TOKEN_KEY }}
        OAUTH_TOKEN_SECRET: ${{ secrets.OAUTH_TOKEN_SECRET }}
        OAUTH_SIGNATURE_METHOD: ${{ secrets.OAUTH_SIGNATURE_METHOD }}
        USER_ID: ${{ secrets.USER_ID }}
        ACCOUNT_ID_V1: ${{ secrets.ACCOUNT_ID_V1 }}
        LAMBDA_UUID_V1: ${{ secrets.LAMBDA_UUID_V1 }}
        CLIENT_ID_V1: ${{ secrets.CLIENT_ID_V1 }}
        CLIENT_SECRET_V1: ${{ secrets.CLIENT_SECRET_V1 }}
        USER_ID_V1: ${{ secrets.USER_ID_V1 }}
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
