

# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish on NPM

on:
  workflow_dispatch:
      inputs:
        version-increment:
          type: choice
          description: 'Version Increment'
          required: true
          options:
            - 'patch'
            - 'minor'
            - 'major'
          default: 'patch'
permissions:
  contents: write
  id-token: write

jobs:
  publish-on-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Versionate
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version ${{ github.event.inputs.version-increment }}

      - name: Build
        run: npm ci
        
      - name: Publish to NPM
        # This command uses the GitHub OIDC token automatically
        run: npm publish --provenance --access public
        env:
          # This tells NPM to use the OIDC-verified session
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          commit-message: Updated repository to ${{ steps.publish.outputs.version }}
          title: Bump version to ${{ steps.publish.outputs.version }}
          body: New release build
          branch: release/${{ steps.publish.outputs.version }}
          base: master
